### ISSUE TITLE
{hacktoberfest} Fix Post Schema

### ISSUE THREAD

**Issue by piyush97** [piyush97/share-here#2]
Issue: Posts shows as [] empty even though there are posts

**Comment by anup-a** [comment]
Can I pick this one?

**Comment by piyush97** [comment]
Sure! Go ahead @anup-a

**Comment by anup-a** [comment]
I cannot reproduce issue on my local machine.  I can createPost and fetch using posts query

**Comment by piyush97** [comment]
open `/graphql` and try to query posts to reproduce the issue
@anup-a :)

**Comment by anup-a** [comment]
Yup thats what I was talking about ...
![image](https://user-images.githubusercontent.com/29516633/94790002-4dac3600-03f3-11eb-8599-94b788812681.png)

**Comment by piyush97** [comment]
Okay! Cool
